# tasks/main.yml
---
- name: Install dependencies
  become: yes
  apt:
    name:
      - wget
      - build-essential
    state: present

- name: Download Zabbix Agent package
  become: yes
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb
    dest: /tmp/zabbix-release.deb
  when: ansible_os_family == "Debian"

- name: Install Zabbix Agent
  become: yes
  apt:
    name: /tmp/zabbix-release.deb
    state: present
  when: ansible_os_family == "Debian"

- name: Configure Zabbix Agent
  become: yes
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart_zabbix_agent

- name: Ensure Zabbix Agent is running and enabled
  become: yes
  service:
    name: zabbix-agent
    state: started
    enabled: yes