---
- hosts: all
  gather_facts: yes
  roles:
    - setup_vm
  become: yes

- hosts: db_servers
  gather_facts: yes
  roles:
    - postgresql_vm
  become: yes

- hosts: backup_server
  gather_facts: yes
  roles:
    - postgresql_vm
  become: yes
