---
- hosts: all
  gather_facts: yes
  roles:
    - setup_vm
    - users_vm
  become: yes

- hosts: db_servers:backup_server
  gather_facts: yes
  roles:
    - postgresql_vm
  become: yes

- hosts: balanser
  gather_facts: yes
  roles:
    - nginx_balancer_vm
  become: yes