# tasks/main.yml
---
- name: Add PostgreSQL repository key
  become: yes
  apt_key:
    url: "{{ pg_repo_key_url }}"
    state: present

- name: Add PostgreSQL repository
  become: yes
  apt_repository:
    repo: "{{ pg_repo_deb_url }}"
    state: present

- name: Update apt cache after adding PostgreSQL repository
  become: yes
  apt:
    update_cache: yes

- name: Install PostgreSQL server
  become: yes
  apt:
    name: ["postgresql-{{ postgres_version }}", "postgresql-contrib-{{ postgres_version }}"]
    state: present

- name: Start and enable PostgreSQL service
  become: yes
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure PostgreSQL data directory exists
  become: yes
  file:
    path: "/var/lib/postgresql/{{ postgres_version }}/main"
    state: directory
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: '0700'

- name: Copy default PostgreSQL configuration (if needed)
  become: yes
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: '0644'
  notify: restart_postgresql

- name: Copy default PostgreSQL pg_hba.conf (if needed)
  become: yes
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: '0644'
  notify: restart_postgresql