---
- name: Configure all servers
  hosts: all
  gather_facts: yes
  roles:
    - setup_vm
    - users_vm
    - zabbix_agent_vm
  become: yes

- name: Configure balancer
  hosts: balanser
  gather_facts: yes
  roles:
    - nginx_balancer_vm
  become: yes